# Generated by Django 5.2.12 on 2026-03-12 05:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('producer', models.CharField(max_length=64)),
                ('task_ref', models.CharField(blank=True, max_length=255)),
                ('job_type', models.CharField(choices=[('transcribe', 'Transcribe')], max_length=32)),
                ('lane', models.CharField(choices=[('batch', 'Batch')], default='batch', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=32)),
                ('backend', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField(default=dict)),
                ('context_data', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='queued', max_length=32)),
                ('django_task_id', models.CharField(blank=True, max_length=64)),
                ('error_detail', models.TextField(blank=True)),
                ('result_text', models.TextField(blank=True)),
                ('result_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['producer', 'task_ref'], name='jobs_job_produce_d9a12d_idx'), models.Index(fields=['state'], name='jobs_job_state_7f24c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('source', 'Source'), ('extracted_audio', 'Extracted audio'), ('transcript_text', 'Transcript text'), ('transcript_json', 'Transcript JSON'), ('transcript_vtt', 'Transcript VTT')], max_length=64)),
                ('format', models.CharField(blank=True, max_length=32)),
                ('storage_backend', models.CharField(max_length=32)),
                ('storage_key', models.CharField(max_length=512)),
                ('content_type', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('exposed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='jobs.job')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('job', 'name'), name='jobs_artifact_job_name_unique')],
            },
        ),
    ]
