# Generated by Django 5.2.12 on 2026-03-14 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_job_type_alter_jobartifact_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='dispatch_mode',
            field=models.CharField(choices=[('sync', 'Sync'), ('batch', 'Batch')], default='batch', max_length=16),
        ),
        migrations.AddField(
            model_name='job',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voxhelm_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobartifact',
            name='kind',
            field=models.CharField(choices=[('source', 'Source'), ('extracted_audio', 'Extracted audio'), ('transcript_text', 'Transcript text'), ('transcript_json', 'Transcript JSON'), ('transcript_vtt', 'Transcript VTT'), ('transcript_dote', 'Transcript DOTe'), ('transcript_podlove', 'Transcript Podlove'), ('speech_wav', 'Speech WAV'), ('speech_mp3', 'Speech MP3'), ('speech_ogg', 'Speech OGG')], max_length=64),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['operator', 'created_at'], name='jobs_job_operato_2e0c28_idx'),
        ),
    ]
