# Generated by Django 5.2.12 on 2026-05-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_stagedmedia'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stagedmedia',
            new_name='jobs_staged_produce_cbe898_idx',
            old_name='jobs_staged_producer_76b546_idx',
        ),
        migrations.RenameIndex(
            model_name='stagedmedia',
            new_name='jobs_staged_expires_b7ff6d_idx',
            old_name='jobs_staged_expires_617032_idx',
        ),
    ]
