# Generated by Django 5.2.12 on 2026-05-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_jobs_staged_producer_76b546_idx_jobs_staged_produce_cbe898_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobartifact',
            name='kind',
            field=models.CharField(choices=[('source', 'Source'), ('extracted_audio', 'Extracted audio'), ('transcript_text', 'Transcript text'), ('transcript_json', 'Transcript JSON'), ('transcript_vtt', 'Transcript VTT'), ('transcript_dote', 'Transcript DOTe'), ('transcript_podlove', 'Transcript Podlove'), ('transcript_speakers', 'Transcript speaker suggestions'), ('speech_wav', 'Speech WAV'), ('speech_mp3', 'Speech MP3'), ('speech_ogg', 'Speech OGG')], max_length=64),
        ),
    ]
