# Generated by Django 5.2.12 on 2026-10-06 13:52

import hashlib
import json

from django.conf import settings
from django.db import migrations, models


# Frozen copy of jobs.fingerprints at the time of this migration, so the backfill stays stable
# even if the runtime fingerprint changes later (such a change needs its own data migration).
def _fingerprint(job):
    if job.job_type != "transcribe":
        material = {"job_type": job.job_type}
    else:
        input_data = job.input_data or {}
        if input_data.get("kind") == "upload":
            input_data = {"kind": "upload", "upload_id": str(input_data.get("upload_id") or "")}
        output_data = job.output_data or {}
        material = {
            "job_type": job.job_type,
            "backend": job.backend,
            "model": job.model,
            "language": job.language or None,
            "input": input_data,
            "output_formats": sorted(output_data.get("formats", [])),
            "diarization": output_data.get("diarization", {"enabled": False}),
        }
    encoded = json.dumps(material, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def backfill_request_fingerprints(apps, schema_editor):
    Job = apps.get_model("jobs", "Job")
    seen_active = set()
    pending = []
    # Materialize first: updating rows while a SQLite cursor is still iterating them is unsafe.
    jobs = list(Job.objects.exclude(task_ref="").order_by("-created_at", "-id"))
    for job in jobs:
        fingerprint = _fingerprint(job)
        if job.state != "failed":
            key = (job.producer, job.task_ref, fingerprint)
            if key in seen_active:
                # Legacy duplicate created by the pre-constraint race. Leave it unfingerprinted so
                # the constraint can be added; the newest matching job keeps the fingerprint.
                continue
            seen_active.add(key)
        job.request_fingerprint = fingerprint
        pending.append(job)
    Job.objects.bulk_update(pending, ["request_fingerprint"], batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_remote_workers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="request_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.RunPython(backfill_request_fingerprints, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("task_ref", ""), _negated=True),
                    models.Q(("request_fingerprint", ""), _negated=True),
                    models.Q(("state", "failed"), _negated=True),
                ),
                fields=("producer", "task_ref", "request_fingerprint"),
                name="jobs_job_active_task_ref_fingerprint_unique",
            ),
        ),
    ]
