# Generated by Django 5.2.12 on 2026-10-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0008_job_request_fingerprint"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingArtifactDeletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("job_id", models.UUIDField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("source", "Source"),
                            ("extracted_audio", "Extracted audio"),
                            ("transcript_text", "Transcript text"),
                            ("transcript_json", "Transcript JSON"),
                            ("transcript_vtt", "Transcript VTT"),
                            ("transcript_dote", "Transcript DOTe"),
                            ("transcript_podlove", "Transcript Podlove"),
                            ("transcript_speakers", "Transcript speaker suggestions"),
                            ("speech_wav", "Speech WAV"),
                            ("speech_mp3", "Speech MP3"),
                            ("speech_ogg", "Speech OGG"),
                        ],
                        max_length=64,
                    ),
                ),
                ("storage_backend", models.CharField(max_length=32)),
                ("storage_key", models.CharField(max_length=512)),
                ("storage_identity", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
